#ifndef SAMPLERS_SH_HEADER_GUARD
#define SAMPLERS_SH_HEADER_GUARD

// Shared

#define SAMPLER_PBR_ALBEDO_LUT 0

#define SAMPLER_PBR_BASECOLOR 1
#define SAMPLER_PBR_METAL 2
#define SAMPLER_PBR_ROUGHNESS 3
#define SAMPLER_PBR_NORMAL 4
#define SAMPLER_PBR_OCCLUSION 5
#define SAMPLER_PBR_EMISSIVE 6

#define SAMPLER_DEFERRED_DIFFUSE_A 7
#define SAMPLER_DEFERRED_NORMAL 8
#define SAMPLER_DEFERRED_F0_METALLIC 9
#define SAMPLER_DEFERRED_EMISSIVE_OCCLUSION 10
#define SAMPLER_DEFERRED_DEPTH 11

#define SAMPLER_SKYBOX_CUBEMAP 12

#endif // SAMPLERS_SH_HEADER_GUARD
